version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: remotelyx_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: remotelyx_dashboard
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/migrations/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - remotelyx_network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: remotelyx_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - remotelyx_network

  # Backend API (Optional - for containerized development)
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: remotelyx_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/remotelyx_dashboard?authSource=admin
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    volumes:
      - ./server:/app
    depends_on:
      - mongodb
      - redis
    networks:
      - remotelyx_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data:
  redis_data:

networks:
  remotelyx_network:
    driver: bridge
